[tool.poetry]
name = "plentyindex"
version = "0.1.0"
description = ""
authors = ["PLENTY"]

[tool.poetry.dependencies]
python = "^3.9"
dipdup = "^3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
